[package]
name = "boom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alto = "3.0.4"
anyhow = "1.0.66"
audio = "0.2.0-alpha.3"
clap = "4.0.19"
cpal = "0.14.1"
rand = "0.8.5"
